---
- hosts: all
  become: yes
  tasks:
   - name: Ensure that rsync RPM is installed on all hosts.
     yum:
       name: rsync
       state: present
- hosts: "{{ dest_host }}"
  tasks:
   - name: Copy Remote-To-Remote (from source_host to  dest_host)
     synchronize:
       rsync_timeout: 10
       src: "{{ source_filepath }}"
       dest: "{{ dest_filepath }}"
     delegate_to: "{{ source_host }}"
