---
- hosts: all
  vars:
    rhsm_username: "someone"
    rhsm_password: "somepassword"
    pool_name: "somepoolid"
  tasks:
    - name: Register to rhsm.
      redhat_subscription:
        state: present
        username: "{{ rhsm_username }}"
        password: "{{ rhsm_password }}"
        auto_attach: no
        pool: "{{ pool_name }}"
