---
- hosts: all
  vars:
    forceoption: no
  tasks:
    - name: Register to rhsm.
      redhat_subscription:
        state: present
        username: "{{ rhsm_username }}"
        password: "{{ rhsm_password }}"
        auto_attach: true
        pool: "{{ pool_name }}"
        force_register: "{{ forceoption }}"
        
    - name: Disable all repositories except rhel-7-server-rpms
      rhsm_repository:
        name: "{{ item }}"
        state: disabled
      with_items: "{{
        rhsm_repository.repositories |
        map(attribute='id') |
        difference(['rhel-7-server-rpms']) }}"
