---
- hosts: all
  vars:
    forceoption: no
  tasks:
    - name: Register to rhsm.
      redhat_subscription:
        state: present
        username: "{{ rhsm_username }}"
        password: "{{ rhsm_password }}"
        auto_attach: true
        pool: "{{ pool_name }}"
        force_register: "{{ forceoption }}"
