---
- hosts: all
  vars:
    forceoption: no
  tasks:
    - name: Register to rhsm.
      redhat_subscription:
        state: present
        username: "{{ rhsm_username }}"
        password: "{{ rhsm_password }}"
        auto_attach: true
        pool: "{{ pool_name }}"
        force_register: "{{ forceoption }}"
        
    - name: Disable all RHSM repositories
      rhsm_repository:
        name: "{{ item }}"
        state: disabled
      with_items:
        - rhel-7-public-beta-rpms
        - rhel-7-server-htb-rpms
      ignore_errors: yes
     
    - name: Enable RHEL 7 rpms repo
      rhsm_repository:
        name: rhel-7-server-rpms
        state: enabled
