---
- hosts: all:!tag_infranode
  vars:
    gather_facts: yes
  tasks:
    - name: Register to rhsm.
      command: "/usr/sbin/subscription-manager status"
      when: ansible_distribution == 'Red Hat Enterprise Linux'
