---
- hosts: all:!tag_infranode
  gather_facts: no
  become: true
  tasks:
    - name: Register machines against Satellite Server
      redhat_subscription:
        state: present
        activationkey: "Register-against-Rhel7"
        org_id: "mylab"
        force_register: yes
        auto_attach: true
        server_hostname: "satellite.mylab.com"
