---
- hosts: all:!tag_infranode
  gather_facts: no
  tasks:
    - name: Register machines against Satellite Server
      command: 'subscription-manager register --org="mylab" --activationkey="Register-against-Rhel7"'
  #    redhat_subscription:
  #      state: present
  #      activationkey: "Register-against-Rhel7"
  #      org_id: "mylab"
  #      force_register: yes
  #      pool: '^(Red Hat Enterprise Server)'
  #      auto_attach: true
  #      server_hostname: "satellite.mylab.com"
