---
- hosts: all:!tag_infranode
  gather_facts: yes
  become: yes
  tasks:
    - name: Check whether this server is registered against Satellite Server
      command: "/usr/sbin/subscription-manager status"
      register: result
      ignore_errors: true
      when: os_type == 'rhel_7x64'
        
    - name: Register any hosts that are not currently subscribed
      ovirt_tag:
        name: "satellite-registered"
        auth:
          hostname: "{{ rhv_server }}"
          insecure: yes
          username: "{{ rhv_user }}"
          password: "{{ rhv_password }}"
        vms: "{{ ansible_hostname }}"
      when: result is succeeded
    
    - name: Register any hosts that are not currently subscribed
      local_action:
        module: ovirt_tag
        name: "satellite-not-registered"
        auth:
          hostname: "{{ rhv_server }}"
          insecure: yes
          username: "{{ rhv_user }}"
          password: "{{ rhv_password }}"
        vms: "{{ ansible_hostname }}"
      when: result is failed
