---
- hosts: all:!tag_infranode
  gather_facts: yes
  become: yes
  tasks:
    - name: Check whether this server is registered against Satellite Server
      command: "/usr/sbin/subscription-manager status"
      register: result
      ignore_errors: true
      when: os_type == 'rhel_7x64'
      
    - name: Tag hosts that are currently subscribed to satellite
      become: false
      block:
        local_action:
          module: ovirt_tag
          name: "satellite-registered"
          state: attached
          auth:
            hostname: "{{ rhv_server }}"
            insecure: yes
            username: "{{ rhv_user }}"
            password: "{{ rhv_password }}"
          vms:
           - "{{ inventory_hostname }}"
         local_action:
          module: ovirt_tag
          name: "satellite-not-registered"
          state: detached
          auth:
            hostname: "{{ rhv_server }}"
            insecure: yes
            username: "{{ rhv_user }}"
            password: "{{ rhv_password }}"
          vms:
           - "{{ inventory_hostname }}"
      when: result is succeeded
    
    - name: Tag hosts that are not currently subscribed to satellite
      become: false
      block:
        local_action:
          module: ovirt_tag
          name: "satellite-not-registered"
          auth:
            hostname: "{{ rhv_server }}"
            insecure: yes
            username: "{{ rhv_user }}"
            password: "{{ rhv_password }}"
          vms:
            - "{{ inventory_hostname }}"
        local_action:
          module: ovirt_tag
          name: "satellite-registered"
          state: detached
          auth:
            hostname: "{{ rhv_server }}"
            insecure: yes
            username: "{{ rhv_user }}"
            password: "{{ rhv_password }}"
          vms:
           - "{{ inventory_hostname }}"
      when: result is failed
